/**"pewawancara_nama": "Puskesmas Rawajati",
"kabupaten_nama": "KOTA ADM. JAKARTA SELATAN",
"puskesmas_nama": "Kel. Rawajati I",
"idkasus": "COV-3174210070",
"status_epi": "Konfirmasi Kontak",
"pasien_status_terakhir": null,
"pasien_nama": "Rasamala",
"pasien_tanggal_lahir": "2019-09-01",
"pasien_usia": 1,
"pasien_jenis_kelamin": "Perempuan",
"pasien_pekerjaan": "Lainnya",
"pasien_latitude": null,
"pasien_longitude": null,
"id": "APdRk4weGy",
"pewawancara_id": "k8mepzrbMy",
"pasien_id": "5xe7VGrd7r",
"tanggal_wawancara": "2021-05-23",
"pe": "[]",
"terdapat_gejala": "0",
"tanggal_gejala": null,
"kurva_epidemiologi": "2021-05-23",
"demam": null,
"batuk": null,
"pilek": null,
"sakit_tenggorokan": null,
"sesak_napas": null,
"sakit_kepala": null,
"lemas": null,
"nyeri_otot": null,
"mual_muntah": null,
"nyeri_abdomen": null,
"diare": null,
"gangguan_menghidu": null,
"gangguan_mengecap": null,
"gejala_lainnya": null,
"ket_gejala_lainnya": null,
"hamil": "0",
"diabetes": "0",
"penyakit_jantung": "0",
"hipertensi": "0",
"keganasan": "0",
"gangguan_imunologi": "0",
"gagal_ginjal": "0",
"gagal_hati": "0",
"ppok": "0",
"komorbid_lainnya": "0",
"ket_komorbid_lainnya": null,
"dirawatdirs": "0",
"namars": null,
"tanggal_masuk_rs": null,
"icu": null,
"intubasi": null,
"emco": null,
"status_terakhir": "Masih Sakit",
"tanggal_meninggal": null,
"pneumonia": "0",
"ards": "0",
"lainnya": "0",
"ket_lainnya": null,
"spesimen": "1",
"jenis_spesimen_1": "1",
"swab_nasofaring_1": null,
"swab_orofaring_1": null,
"sputum_1": null,
"serum_1": null,
"tanggal_pengambilan_1": "2021-05-23",
"tanggal_pengambilan_keluar_1": "2021-05-24",
"hasil_pemeriksaan_spesimen_1": "Positif",
"jenis_spesimen_2": "0",
"swab_nasofaring_2": null,
"swab_orofaring_2": null,
"sputum_2": null,
"serum_2": null,
"tanggal_pengambilan_2": null,
"tanggal_pengambilan_keluar_2": null,
"hasil_pemeriksaan_spesimen_2": null,
"pemeriksaan_rdt_antigen": 0,
"tanggal_pemeriksaan_rdt_antigen": null,
"tanggal_pemeriksaan_rdt_antigen2": null,
"hasil_pemeriksaan_rdt_antigen2": null,
"hasil_pemeriksaan_rdt_antigen": null,
"keluar_negeri": "0",
"transmisi_lokal": "0",
"kunjungan_faskes": "0",
"pasar_hewan": "0",
"kontak_suspek": "0",
"kontak_konfirmasi": "0",
"ispa_berat": "0",
"petugas_kesehatan": "0",
"apd": null,
"gown": null,
"masker": null,
"sarung_tangan": null,
"maskerniosn": null,
"ffp3": null,
"goggle": null,
"tidak_memakai_apd": null,
"aerosol": null,
"kontak_erat": "1",
"sync": 1,
"status_epidemiologi": "Suspek",
"tanggal_laporan_konfirmasi": null,
"last_step": "COMPLETE",
"status": "COMPLETE",
"created_at": "2021-05-31 07:34:58",
"updated_at": "2021-05-31 07:34:58"
**/
export class PenyelidikanEpi {
  id: string;
  tanggalWawancara: Date;
  terdapatGejala: boolean;
  tanggalGejala: Date;
  kurvaEpidemiologi: Date;
  demam: boolean;
  batuk: boolean;
  pilek: boolean;
  sakitTenggorokan: boolean;
  sesakNapas: boolean;
  sakitKepala: boolean;
  lemas: boolean;
  nyeriOtot: boolean;
  mualMuntah: boolean;
  nyeriAbdomen: boolean;
  diare: boolean;
  gangguanMenghidu: boolean;
  gangguanMengecap: boolean;
  gejalaLainnya: boolean;
  ketGejalaLainnya: string;
  hamil: boolean;
  diabetes: boolean;
  penyekitJantung: boolean;
  hipertensi: boolean;
  keganasan: boolean;
  gangguanImmunologi: boolean;
  gagalGinjal: boolean;
  gagalHati: boolean;
  ppok: boolean;
  komorbidLainnya: boolean;
  ketKomorbidLainnya: boolean;
  dirawatdirs: boolean;
  namars: string;
  tanggalMasukRs: Date;
  icu: boolean;
  intubasi: boolean;
  emco: boolean;
  statusTerakhir: string;
  tanggalMeninggal: Date;
  pneumonia: boolean;
  ards: boolean;
  lainnya: boolean;
  ketLainnya: string;
  spesimen: boolean;
  jenisSpesimen1: boolean;
  swabNasofaring1: boolean;
  swabOrofaring1: boolean;
  sputum1: boolean;
  serum1: boolean;
  tanggalPengambilan1: Date;
  tanggalPengambilanKeluar1: Date;
  hasilPemeriksaanSpesimen1: string;
  jenisSpesimen2: boolean;
  swabNasofaring2: boolean;
  swabOrofaring2: boolean;
  sputum2: boolean;
  serum2?: boolean;
  tanggalPengambilan2?: Date;
  tanggalPengambilanKeluar2?: Date;
  hasilPemeriksaanSpesimen2?: string;
  pemeriksaanRdtAntigen?: boolean;
  tanggalPemeriksaanRdtAntigen?: Date;
  hasilPemeriksaanRdtAntigen?: string;
  tanggalPemeriksaanRdtAntigen2?: Date;
  hasilPemeriksaanRdtAntigen2?: Date;
  keluarNegeri?: boolean;
  transmisiLokal?: boolean;
  kunjunganFaskes?: boolean;
  pasarHewan?: boolean;
  kontakSuspek?: boolean;
  kontakKonfirmasi?: boolean;
  ispaBerat?: boolean;
  petugasKesehatan?: boolean;
  apd?: boolean;
  gown?: boolean;
  masker?: boolean;
  sarungTangan?: boolean;
  maskerniosn?: boolean;
  ffp3?: boolean;
  goggle?: boolean;
  tidakMemakaiApd?: boolean;
  aerosol?: boolean;
  kontakErat?: number;
  statusEpidemiologi?: string;
  tanggalLaporanKonfirmasi?: Date;
  status?: string;
  createdAt: Date;
  updatedAt: Date;
}
